### PR TITLE
Only send mail after succesful payment

### PR DESCRIPTION
**Pull request by runelaenen**
## Summary
Disabled sending email before payment and sends it when payment is succesfull.

## Tested scenarios
Payment with CC: failed, success
Paymetn with sofort: failed, success

**Fixed issue**:  #12

### CODE REVIEW

**Review by acampos1916 — CHANGES_REQUESTED** [review]
Looks alright! Indentation seems off in the .xmls but good otherwise.

**Comment by cyattilakiss** [comment]
Hi @runelaenen 
Could you please give a look to this comment: https://github.com/Adyen/adyen-shopware5/pull/46#pullrequestreview-480565141
Thanks! :)

**Review by msilvagarcia — APPROVED** [review]

**Review by acampos1916 — APPROVED** [review]

**Comment by sanderjcda** [comment]
Hi, unfortunately I'm still experiencing problems with sending the order confirmation emails too early:
**Shopware 5.6.8** _(fresh installation with only one active plugin: Adyen Shopware Plugin)_
**Adyen Shopware Plugin 1.5.1** _(Adyen test environment is set)_

Tested with Klarna, when redirected to the playground.klarna.com environment I do receive immediately an order confirmation email. Even before I have made a choice in the Klarna screen. _('go back' or 'buy')_
Also with the iDeal _"test issuer cancelled"_ method I do receive an order confirmation email.
When continuing in both cases _(Klarna/iDeal)_ I will be returned to my filled shopping cart.

**Comment by muhkuh2005** [comment]
I can confirm the email being sent as we are experiencing the same.
How to reproduce:
* Enter correct Creditcard number and expiry
* Enter wrong CVC/CVV
* Submit order

Error message:
`Your transaction was refused by the Payment Service Provider.`
Order confirmation email has been sent

**Pull request merged**
